### ISSUE TITLE
Change Icons

### ISSUE THREAD

**Issue by InfernoX5515** [InfernoX5515/Spatial-SocialNetworks#16]
Change icons to display the same application-wide. For example, colors, symbols, etc. should match for the user plotted on both graphs

**Comment by InfernoX5515** [comment]
If you could also look into changing the query user to green (and possibly a star?) on the summary social network graph too that would be great! Maybe talk to @ghulvey about this if you have issues, he was the one who implemented that graph.

![image](https://user-images.githubusercontent.com/80545420/191400722-89f82de4-4989-4b7a-b9bc-dfa14d4d31c3.png)

**Comment by szuelzke** [comment]
Ok thank you! So far I have simply changed the color of the icon on the road network for the selected query user to match the color/shape icon on the summary graph. So now the selected query user on both graphs is a green star.

**Comment by InfernoX5515** [comment]
Color has been changed. There was code that was overriding the query user and marking it as blue.
