### ISSUE TITLE
Combo-List for Query User

### ISSUE THREAD

**Issue by InfernoX5515** [InfernoX5515/Spatial-SocialNetworks#19]
Change how query users are chosen. Instead of buttons, use a combo-list (dropdown with a list to select users from), Then, display info about the user selected on the right. This info will be linked to issue #18

**Comment by ghulvey** [comment]
- Add the user's name to the combo box
- Look into adding sort functionality
- Fix the spacing

**Comment by ghulvey** [comment]
Split into multiple issues, closing.
