### ISSUE TITLE
Query User Displayed Twice

### ISSUE THREAD

**Issue by InfernoX5515** [InfernoX5515/Spatial-SocialNetworks#31]
When selecting a query user on the main graph and then switching to the summary and re-selecting a query user, the first user still shows. This results in two users being marked on the graph. This does not happen the other way around (choosing in summary then choosing in normal).

![image](https://user-images.githubusercontent.com/80545420/191401228-5e899f96-0af7-4848-864a-1e8241c5b7f9.png)

**Comment by ghulvey** [comment]
Investigating
