### ISSUE TITLE
Change query user information box

### ISSUE THREAD

**Issue by InfernoX5515** [InfernoX5515/Spatial-SocialNetworks#35]
This is last week's note so if this is complete please just close the issue.

This was a suggestion to make the user information display in the same type of box as the users/keywords. If this isn't possible or you think this is not a good idea, you can also just close the issue with a not planned status

**Comment by ghulvey** [comment]
The reason the lists have white backgrounds are that they are user inputs. It is probably not best to convert the data field to input elements as the user could modify the values.
